# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

# Site settings
title: Harbot
description: "The most accessible 401(k)"
keywords: fintech, news, media
email: tripathi@vesthq.com
url: http://www.harborhq.com
repository: https://github.com/vesthq/harbor
google_analytics: UA-72011621-1
