# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

# Site settings
title: HarborHQ
description: "All-in-one 401(k) plan"
keywords: affordable, modern, 401(k), retirement 
email: tripathi@vesthq.com
url: http://www.harborhq.com
repository: https://github.com/VestHQ/Harbor
# google_analytics: UA-72011621-1
